

export const ADD_TODO_ACTION: 'ADD_TODO_ACTION' = 'ADD_TODO_ACTION';
export const REMOVE_TODO_ACTION: 'REMOVE_TODO_ACTION' = 'REMOVE_TODO_ACTION';
export const CHECK_TASK_ACTION: 'CHECK_TASK_ACTION' = 'CHECK_TASK_ACTION';